### ISSUE TITLE
Revision by @paulasoroetaarizcuren

### ISSUE THREAD

**Issue by mberasategi** [MSGW2018/A6#35]
- [x] [Journalism: Changes](https://github.com/MSGW2018/A6/blob/master/journalism/changes.md)
- [x] [Journalism: Functions](https://github.com/MSGW2018/A6/blob/master/journalism/functions.md)
- [x] [Journalism: Future](https://github.com/MSGW2018/A6/blob/master/journalism/future.md)

**Comment by paulasoroetaarizcuren** [comment]
The changes that I have made in the first part: Journalism Changes are the following:

I have added a video about social networks and their influence on journalism and an article on digital journalism. 

I decided to make these two contributions because I think they bring more knowledge to the article

**Comment by paulasoroetaarizcuren** [comment]
In the second part I made the following changes: on the one hand I added a link to a video about the functions of the journalist. In addition, in each section I have gone a little deeper into the information provided by the article and I have corrected some grammatical issues.

**Comment by paulasoroetaarizcuren** [comment]
Finally in the third part I added more information in some sections in order to increase the knowledge on the subject.
