### ISSUE TITLE
Revision by @elenavalverde

### ISSUE THREAD

**Issue by mberasategi** [MSGW2018/A6#38]
- [x] [Knowledge generation: Collective intelligence](https://github.com/MSGW2018/A6/blob/master/knowledge-generation/collective-intelligence.md)
- [x] [Knowledge generation: Open data](https://github.com/MSGW2018/A6/blob/master/knowledge-generation/open-data.md)
- [x] [Knowledge generation: Ordering the digital disorder](https://github.com/MSGW2018/A6/blob/master/knowledge-generation/ordering-digital-disorder.md)

**Comment by elenavalverde** [comment]
I made a few grammar and orthography corrections. Also, I added some pictures and modified the size of one of them. Then, I moved some links to other words and corrected the visual structure of the "Open data" section, because all the content was in a single paragraph. Anyway, the content is very well chosen and organised. Good job!

**Comment by mberasategi** [comment]
Now you have finished all the revisions assigned to you please go ahead and **open a pull request** [as described in the CONTRIBUTING document](https://github.com/MSGW2018/A6/blob/master/CONTRIBUTING.md#stage-2-revision).

**Comment by elenavalverde** [comment]
Hi @mberasategi , I'm about to create the pull request for my revision but I can't find the number of the group that did the content I revised. It is the one that did the content about "Knowledge generation". Could you help me please? Thanks.

**Comment by mberasategi** [comment]
Hi @elenavalverde , it's @MSGW2018/group7 .

**Comment by elenavalverde** [comment]
Thanks @mberasategi . The pull request is now done.
